---
layout:     post                    # 使用的布局（不需要改）
title:      无需看源码了解并解决一个事务常见的异常        # 标题
subtitle:   无需看源码了解并解决一个事务常见的异常        #副标题
date:       2019-11-13          # 时间
author:     不学无数                      # 作者
header-img: img/post-bg-e2e-ux.jpg    #这篇文章标题背景图片
catalog: true                       # 是否归档
tags:                               #标签
    - Spring
    - 事务
---

# 无需看源码了解并解决一个事务常见的异常

在观看此篇文章之前需要了解什么是[事务的传播属性](https://juejin.im/post/5da6eee2f265da5bb977d65c)

在观看此篇文章之前需要了解什么是[事务的传播属性](https://juejin.im/post/5da6eee2f265da5bb977d65c)

在观看此篇文章之前需要了解什么是[事务的传播属性](https://juejin.im/post/5da6eee2f265da5bb977d65c)


> Transaction rolled back because it has been marked as rollback-only

相信大家在使用Spring事务的时候有概率会碰到一个异常，这个异常就是`UnexpectedRollbackException`异常的描述就是上面所写的。至于这个异常是怎么报出来的呢？我们先模拟出来，然后进行着手分析。我们模拟的场景是转钱的场景，即A给B转100块钱。

```

@Service
public class UserAccountA {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private UserAccountB userAccountB;

    @Transactional
    public void eventTwo() throws RollbackException {
        jdbcTemplate.execute("UPDATE USER SET MONEY = MONEY - 100 WHERE NAME = 'A'");
        userAccountB.eventTwo();
    }

}

```

```
@Service
public class UserAccountB {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Transactional(propagation = Propagation.REQUIRED,rollbackFor = RollbackException.class)
    public void eventTwo() throws RollbackException {
        jdbcTemplate.execute("UPDATE USER SET MONEY = MONEY + 100 WHERE NAME = 'B'");
        throw new RollbackException();
    }

}

```

```
public class RollbackException extends Exception {
}


```

上面的三个类分别是用户A、用户B、和自定义的异常。这时候我们运行程序的时候就能看到那个异常了。那么为什么会报此异常呢。这里我们有两个需要注意的点。

* 用户B定义的传播属性：`Propagation.REQUIRED `此传播属性下的意思就是支持当前事务，如果当前没有事务那么就新建事务，如果有事务就加入此事务。**所以此时B方法加入到了A方法创建的事务中**
* 自定义异常类：我们自定义的异常类是继承了`Exception`。下面的是官方文档的一句话，意思就是默认情况下当抛出`RuntimeException`才会回滚。

> By default, a transaction will be rolling back RuntimeException and Error

有了上面两个知识的补充，下面我们开始讲为什么会报这个异常，我们都知道Spring的事务其实是用了动态搭理的原理实现的。

![](/img/pageImg/无需看源码了解并解决一个事务常见的异常0.jpg)

大概嵌套逻辑就像上图一样，但是在B方法执行完成以后抛出了异常，需要回滚，但是并不会真正的回滚，而是将此事务标记为`rollback-only`，当A方法执行完以后，我们可以看到在A方法上面并没有`rollbackFor`这个参数设置，而抛出的异常也是继承了`Exception`所以A方法执行完以后想要提交事务，所以此时就会产生冲突。

> 同一个事务中，一个方法想要回滚，一个方法想要提交。当然会抛异常了。


## 解决办法

解决办法很简单，首先我们看是什么导致了这个问题。**同一个事务中，一个方法想要回滚，一个方法想要提交。**。导致这个问题原因有两个。

1. 同一个事务
2. 一个想要回滚，一个想要提交

所以针对上面原因我们可以有两种不同的解决方法。

1. 将B方法的传播属性改为`PROPAGATION_REQUIRES_NEW`，即不会和A共用一个事务，会自己新启动一个事务。此时A和B两个方法互不干扰。
2. 在A方法上的事务注解上加上`rollbackFor = RollbackException.class`参数，此时A方法收到B方法抛出的异常后，也会回滚了。

## [本文代码地址](https://github.com/modouxiansheng/Doraemon)


